SELECT BOARD_NO, BOARD_TITLE, MEMBER_NM, READ_COUNT,
CASE 
	WHEN SYSDATE - CREATE_DT < 1/24/60
	THEN FLOOR((SYSDATE - CREATE_DT) * 24 * 60 * 60) || '초 전'
	WHEN SYSDATE - CREATE_DT < 1/24
	THEN FLOOR((SYSDATE - CREATE_DT) * 24 * 60) || '분 전'
	WHEN SYSDATE - CREATE_DT < 1
	THEN FLOOR ((SYSDATE - CREATE_DT) * 24) || '시간 전'
	ELSE TO_CHAR(CREATE_DT, 'YYYY-MM_DD')
END CREATE_DT, 
(SELECT COUNT(*)
FROM "COMMENT" C
WHERE C.BOARD_NO = B.BOARD_NO)COMMENT_COUNT
FROM BOARD B
JOIN MEMBER USING(MEMBER_NO)
WHERE DELETE_FL = 'N'
ORDER BY BOARD_NO DESC;

SELECT *
FROM MEMBER;