SELECT MEMBER_NO ,MEMBER_ID  , MEMBER_NM , MEMBER_GENDER , TO_CHAR(ENROLL_DATE, 'YYYY-MM-DD') ENROLL_DATE 
FROM MEMBER
WHERE MEMBER_ID = 'user01';

SELECT MEMBER_ID, MEMBER_NM , MEMBER_GENDER 
FROM MEMBER;

SELECT COMMENT_NO, COMMENT_CONTENT, MEMBER_NO, MEMBER_NM,
	   TO_CHAR(CREATE_DT, 'YYYY-MM-DD HH24:MI:SS') CREATE_DT
FROM "COMMENT"
JOIN MEMBER USING(MEMBER_NO)
WHERE DELETE_FL = 'N'
AND BOARD_NO = ?
ORDER BY COMMENT_NO;

SELECT *
FROM MEMBER ;

INSERT INTO BOARD(BOARD_NO, BOARD_TITLE, BOARD_CONTENT, MEMBER_NO)
	VALUES(6, 'hi', 'hi', 2)